export enum HTTP_METHODS { GET, POST, PUT, PATCH, DELETE }

export enum UPDATE_METHODS { UPDATE, REPLACE }

export enum API_SCOPE { USER, DATA }

export enum FILTER_OPERATORS {
  EQUALS,
  LIKE,
  GREATER_THAN,
  LESS_THAN,
  GREATER_THAN_EQUAL,
  LESS_THAN_EQUAL,
  BETWEEN,
  BEGINS_WITH,
  ENDS_WITH,
  CONTAINS,
}

export enum ROLES { Admin, Privileged, Participant }
